name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ubuntu-wheels:
    uses: ./.github/workflows/build-ubuntu.yml
  
  build-macos-wheels:
    uses: ./.github/workflows/build-macos.yml
  
  test-ubuntu-wheels:
    needs: build-ubuntu-wheels
    uses: ./.github/workflows/test-ubuntu.yml
  
  test-macos-wheels:
    needs: build-macos-wheels
    uses: ./.github/workflows/test-macos.yml
